# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy the project files into the container
COPY . /app

# Install dependencies without running any prepare scripts
RUN pip install --no-cache-dir .

# Expose a port if needed (not necessary for stdio-based servers, but might be used by MCP Inspector)
# EXPOSE 8000

# Command to run the MCP-Grep server
CMD ["mcp-grep-server"]
